name: analysis
channels:
  - defaults
  - conda-forge --all
dependencies:
  - root
  - pip
  - uproot3
  - uproot
  - awkward
  - pandas
  - numpy
  - matplotlib
  - lmfit
  - scikit-learn
  - pip:
      - vector
