name: analysis
channels:
  - defaults:
      - gcc_linux-64
  - conda-forge
dependencies:
  - root
  - pip
  - uproot3
  - uproot
  - awkward
  - pandas
  - numpy
  - matplotlib
  - lmfit
  - scikit-learn
  - pip:
      - vector
