name: analysis
channels:
  - conda-forge
dependencies:
  - root
  - pip
  - uproot3
  - uproot
  - awkward
  - vector
  - pandas
  - numpy
  - matplotlib
  - lmfit
  - scikit-learn
  - pip:
      - vector
