name: Python package

on: 
  push:
  pull_request:
  schedule:
    - cron: '* * 1 * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Ensure Clean Notebook
      uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
      with:
        disable-checks: outputs,execution_count
